### ISSUE TITLE
Ds4 gyro hope?

### ISSUE THREAD

**Issue by blamarche** [bwRavencl/X-Gamepad#1]
Any hope of using the gyro in a DS4 controller to map to xplane pitch/roll axes? I attempted to do it via steam controller config but steam uses xinput so the axes don't show in Xplane.

**Comment by bwRavencl** [comment]
In principle usage of the gyro for pitch and roll would be possible, by obtaining the the gyro sensor data via HID - analogous to how DS4 touchpad support is implemented for Linux.
Since I personally have no usage for this feature and am very limited in time, I'd encourage you to perform the necessary implementation yourself.
